
globs_P_10 <- c(paste0("static int nE = ",nE,";"),
           paste0("static int nL1 = ",nL1,";"),
           paste0("static int nL2 = ",nL2,";"),
           paste0("static int nL3 = ",nL3,";"),
           paste0("static int nL4 = ",nL4,";"),
           paste0("static int nL5 = ",nL5,";"),
           paste0("static int nDL5 = ",nDL5,";"),
           paste0("static int nP = ",10,";"),
           paste0("static int nAr = ",nAr,";"))

init_P_10 <-function(params,t0,...)
{
  c(E = rep(0, nE),
    L1 = rep(0,nL1),
    L2 = rep(0,nL2),
    L3 = rep(0,nL3),
    L4 = rep(0,nL4),
    L5 = rep(0,nL5),
    DIAL5 =rep(30,nDL5), #Starting out with 30 diapausing larvae in each nDL5 compartment
    P = rep(0,10),
    Ar = rep(0,nAr),
    As = 0)}

globs_P_5 <- c(paste0("static int nE = ",nE,";"),
                paste0("static int nL1 = ",nL1,";"),
                paste0("static int nL2 = ",nL2,";"),
                paste0("static int nL3 = ",nL3,";"),
                paste0("static int nL4 = ",nL4,";"),
                paste0("static int nL5 = ",nL5,";"),
                paste0("static int nDL5 = ",nDL5,";"),
                paste0("static int nP = ",5,";"),
                paste0("static int nAr = ",nAr,";"))

init_P_5 <-function(params,t0,...)
{
  c(E = rep(0, nE),
    L1 = rep(0,nL1),
    L2 = rep(0,nL2),
    L3 = rep(0,nL3),
    L4 = rep(0,nL4),
    L5 = rep(0,nL5),
    DIAL5 =rep(30,nDL5), #Starting out with 30 diapausing larvae in each nDL5 compartment
    P = rep(0,5),
    Ar = rep(0,nAr),
    As = 0)}


POMP_CM_HOT_P10<- pomp(covartable_hot,
                   times="time",
                   t0=1,
                   globals=globs_P_10,
                   dmeasure = NULL,
                   covar =COVAR_HOT,
                   covarnames = c("TT", "PP_DIFF"),
                   obsnames = c("ARC"),
                   rinit = init_P_10 ,
                   skeleton = vectorfield(DIA_SKEL),
                   paramnames= 
                     c("alphaE_a",
                       "alphaE_b",
                       "alphaE_c",
                       "alphaL1_a",
                       "alphaL1_b",
                       "alphaL1_c",
                       "alphaL2_a",
                       "alphaL2_b",
                       "alphaL2_c",
                       "alphaL3_a",
                       "alphaL3_b",
                       "alphaL3_c",
                       "alphaL4_a",
                       "alphaL4_b",
                       "alphaL4_c",
                       "alphaL5_a",
                       "alphaL5_b",
                       "alphaL5_c",
                       "alphaP_a",
                       "alphaP_b",
                       "alphaP_c",
                       "alphaDL_a",
                       "alphaDL_b",
                       "alphaDL_c",
                       "alphaA_a",
                       "alphaA_b",
                       "alphaA_c",
                       "MORT_E_A","MORT_E_B",'T_E_OPT',
                       "MORT_L_A","MORT_L_B",'T_L_OPT',
                       "MORT_P_A","MORT_P_B","T_P_OPT",
                       "MORT_A_A","MORT_A_B","T_A_OPT",
                       "MORT_DL_A","MORT_DL_B",'T_DL_OPT',
                       "DIA_A","DIA_B","DIA_C","C",'COMP'),
                   statenames=c(sprintf("E%1d",seq_len(nE)),
                                sprintf("L1%1d",seq_len(nL1)),
                                sprintf("L2%1d",seq_len(nL2)),
                                sprintf("L3%1d",seq_len(nL3)),
                                sprintf("L4%1d",seq_len(nL4)),
                                sprintf("L5%1d",seq_len(nL5)),
                                sprintf("DIAL5%1d",seq_len(nDL5)),
                                sprintf("P%1d",seq_len(10)),
                                sprintf("Ar%1d",seq_len(nAr)),
                                "As"))
TRAJ_MODEL_HOT_P_10<- trajectory(POMP_CM_HOT_P10,
                            PARAMETERS
                            ,times=seq(1,12054),
                            format = 'data.frame',method = 'bdf')


POMP_CM_HOT_P5<- pomp(covartable_hot,
                       times="time",
                       t0=1,
                       globals=globs_P_5,
                       dmeasure = NULL,
                       covar =COVAR_HOT,
                       covarnames = c("TT", "PP_DIFF"),
                       obsnames = c("ARC"),
                       rinit = init_P_5 ,
                       skeleton = vectorfield(DIA_SKEL),
                       paramnames= 
                         c("alphaE_a",
                           "alphaE_b",
                           "alphaE_c",
                           "alphaL1_a",
                           "alphaL1_b",
                           "alphaL1_c",
                           "alphaL2_a",
                           "alphaL2_b",
                           "alphaL2_c",
                           "alphaL3_a",
                           "alphaL3_b",
                           "alphaL3_c",
                           "alphaL4_a",
                           "alphaL4_b",
                           "alphaL4_c",
                           "alphaL5_a",
                           "alphaL5_b",
                           "alphaL5_c",
                           "alphaP_a",
                           "alphaP_b",
                           "alphaP_c",
                           "alphaDL_a",
                           "alphaDL_b",
                           "alphaDL_c",
                           "alphaA_a",
                           "alphaA_b",
                           "alphaA_c",
                           "MORT_E_A","MORT_E_B",'T_E_OPT',
                           "MORT_L_A","MORT_L_B",'T_L_OPT',
                           "MORT_P_A","MORT_P_B","T_P_OPT",
                           "MORT_A_A","MORT_A_B","T_A_OPT",
                           "MORT_DL_A","MORT_DL_B",'T_DL_OPT',
                           "DIA_A","DIA_B","DIA_C","C",'COMP'),
                       statenames=c(sprintf("E%1d",seq_len(nE)),
                                    sprintf("L1%1d",seq_len(nL1)),
                                    sprintf("L2%1d",seq_len(nL2)),
                                    sprintf("L3%1d",seq_len(nL3)),
                                    sprintf("L4%1d",seq_len(nL4)),
                                    sprintf("L5%1d",seq_len(nL5)),
                                    sprintf("DIAL5%1d",seq_len(nDL5)),
                                    sprintf("P%1d",seq_len(5)),
                                    sprintf("Ar%1d",seq_len(nAr)),
                                    "As"))
TRAJ_MODEL_HOT_P_5<- trajectory(POMP_CM_HOT_P5,
                                 PARAMETERS
                                 ,times=seq(1,12054),
                                 format = 'data.frame',method = 'bdf')


save(TRAJ_MODEL_HOT_P_10, file = "TRAJ_MODEL_HOT_P_10.RData")
save(TRAJ_MODEL_HOT_P_5, file ='TRAJ_MODEL_HOT_P_5.RData')
####################################################
################DIAPAUSING LARVAE ##################
####################################################


globs_DL_10 <- c(paste0("static int nE = ",nE,";"),
                paste0("static int nL1 = ",nL1,";"),
                paste0("static int nL2 = ",nL2,";"),
                paste0("static int nL3 = ",nL3,";"),
                paste0("static int nL4 = ",nL4,";"),
                paste0("static int nL5 = ",nL5,";"),
                paste0("static int nDL5 = ",10,";"),
                paste0("static int nP = ",nP,";"),
                paste0("static int nAr = ",nAr,";"))


init_DL_10 <-function(params,t0,...)
{
  c(E = rep(0, nE),
    L1 = rep(0,nL1),
    L2 = rep(0,nL2),
    L3 = rep(0,nL3),
    L4 = rep(0,nL4),
    L5 = rep(0,nL5),
    DIAL5 =rep(75,10), #Starting out with 75 diapausing larvae in each nDL5 compartment
    P = rep(0,10),
    Ar = rep(0,nAr),
    As = 0)}

globs_DL_5 <- c(paste0("static int nE = ",nE,";"),
               paste0("static int nL1 = ",nL1,";"),
               paste0("static int nL2 = ",nL2,";"),
               paste0("static int nL3 = ",nL3,";"),
               paste0("static int nL4 = ",nL4,";"),
               paste0("static int nL5 = ",nL5,";"),
               paste0("static int nDL5 = ",5,";"),
               paste0("static int nP = ",nP,";"),
               paste0("static int nAr = ",nAr,";"))



init_DL_5 <-function(params,t0,...)
{
  c(E = rep(0, nE),
    L1 = rep(0,nL1),
    L2 = rep(0,nL2),
    L3 = rep(0,nL3),
    L4 = rep(0,nL4),
    L5 = rep(0,nL5),
    DIAL5 =rep(150,5), #Starting out with 150 diapausing larvae in each nDL5 compartment
    P = rep(0,10),
    Ar = rep(0,nAr),
    As = 0)}

POMP_CM_HOT_D10<- pomp(covartable_hot,
                       times="time",
                       t0=1,
                       globals=globs_DL_10,
                       dmeasure = NULL,
                       covar =COVAR_HOT,
                       covarnames = c("TT", "PP_DIFF"),
                       obsnames = c("ARC"),
                       rinit = init ,
                       skeleton = vectorfield(DIA_SKEL),
                       paramnames= 
                         c("alphaE_a",
                           "alphaE_b",
                           "alphaE_c",
                           "alphaL1_a",
                           "alphaL1_b",
                           "alphaL1_c",
                           "alphaL2_a",
                           "alphaL2_b",
                           "alphaL2_c",
                           "alphaL3_a",
                           "alphaL3_b",
                           "alphaL3_c",
                           "alphaL4_a",
                           "alphaL4_b",
                           "alphaL4_c",
                           "alphaL5_a",
                           "alphaL5_b",
                           "alphaL5_c",
                           "alphaP_a",
                           "alphaP_b",
                           "alphaP_c",
                           "alphaDL_a",
                           "alphaDL_b",
                           "alphaDL_c",
                           "alphaA_a",
                           "alphaA_b",
                           "alphaA_c",
                           "MORT_E_A","MORT_E_B",'T_E_OPT',
                           "MORT_L_A","MORT_L_B",'T_L_OPT',
                           "MORT_P_A","MORT_P_B","T_P_OPT",
                           "MORT_A_A","MORT_A_B","T_A_OPT",
                           "MORT_DL_A","MORT_DL_B",'T_DL_OPT',
                           "DIA_A","DIA_B","DIA_C","C",'COMP'),
                       statenames=c(sprintf("E%1d",seq_len(nE)),
                                    sprintf("L1%1d",seq_len(nL1)),
                                    sprintf("L2%1d",seq_len(nL2)),
                                    sprintf("L3%1d",seq_len(nL3)),
                                    sprintf("L4%1d",seq_len(nL4)),
                                    sprintf("L5%1d",seq_len(nL5)),
                                    sprintf("DIAL5%1d",seq_len(10)),
                                    sprintf("P%1d",seq_len(nP)),
                                    sprintf("Ar%1d",seq_len(nAr)),
                                    "As"))
TRAJ_MODEL_HOT_DL_10<- trajectory(POMP_CM_HOT_D10,
                                 PARAMETERS
                                 ,times=seq(1,12054),
                                 format = 'data.frame',method = 'bdf')


POMP_CM_HOT_DL5<- pomp(covartable_hot,
                      times="time",
                      t0=1,
                      globals=globs_DL_5,
                      dmeasure = NULL,
                      covar =COVAR_HOT,
                      covarnames = c("TT", "PP_DIFF"),
                      obsnames = c("ARC"),
                      rinit = init_DL_5 ,
                      skeleton = vectorfield(DIA_SKEL),
                      paramnames= 
                        c("alphaE_a",
                          "alphaE_b",
                          "alphaE_c",
                          "alphaL1_a",
                          "alphaL1_b",
                          "alphaL1_c",
                          "alphaL2_a",
                          "alphaL2_b",
                          "alphaL2_c",
                          "alphaL3_a",
                          "alphaL3_b",
                          "alphaL3_c",
                          "alphaL4_a",
                          "alphaL4_b",
                          "alphaL4_c",
                          "alphaL5_a",
                          "alphaL5_b",
                          "alphaL5_c",
                          "alphaP_a",
                          "alphaP_b",
                          "alphaP_c",
                          "alphaDL_a",
                          "alphaDL_b",
                          "alphaDL_c",
                          "alphaA_a",
                          "alphaA_b",
                          "alphaA_c",
                          "MORT_E_A","MORT_E_B",'T_E_OPT',
                          "MORT_L_A","MORT_L_B",'T_L_OPT',
                          "MORT_P_A","MORT_P_B","T_P_OPT",
                          "MORT_A_A","MORT_A_B","T_A_OPT",
                          "MORT_DL_A","MORT_DL_B",'T_DL_OPT',
                          "DIA_A","DIA_B","DIA_C","C",'COMP'),
                      statenames=c(sprintf("E%1d",seq_len(nE)),
                                   sprintf("L1%1d",seq_len(nL1)),
                                   sprintf("L2%1d",seq_len(nL2)),
                                   sprintf("L3%1d",seq_len(nL3)),
                                   sprintf("L4%1d",seq_len(nL4)),
                                   sprintf("L5%1d",seq_len(nL5)),
                                   sprintf("DIAL5%1d",5),
                                   sprintf("P%1d",seq_len(nP)),
                                   sprintf("Ar%1d",seq_len(nAr)),
                                   "As"))
TRAJ_MODEL_HOT_DL_5<- trajectory(POMP_CM_HOT_DL5,
                                PARAMETERS
                                ,times=seq(1,12054),
                                format = 'data.frame',method = 'bdf')

